const datatypes = [{ label: 'Patient Care Experience', insertText: '["Patient Care Experience"]' },
  { label: 'Patient Characteristic Payer', insertText: '["Patient Characteristic Payer"]' },
  { label: 'Patient Characteristic Sex', insertText: '["Patient Characteristic Sex"]' },
  { label: 'Patient Characteristic Ethnicity', insertText: '["Patient Characteristic Ethnicity"]' },
  { label: 'Patient Characteristic Race', insertText: '["Patient Characteristic Race"]' },
  { label: 'Medication, Discharge', insertText: '["Medication, Discharge"]' },
  { label: 'Family History', insertText: '["Family History"]' },
  { label: 'Symptom', insertText: '["Symptom"]' },
  { label: 'Immunization, Administered', insertText: '["Immunization, Administered"]' },
  { label: 'Immunization, Order', insertText: '["Immunization, Order"]' },
  { label: 'Diagnosis', insertText: '["Diagnosis"]' },
  { label: 'Assessment, Recommended', insertText: '["Assessment, Recommended"]' },
  { label: 'Assessment, Performed', insertText: '["Assessment, Performed"]' },
  { label: 'Adverse Event', insertText: '["Adverse Event"]' },
  { label: 'Allergy/Intolerance', insertText: '["Allergy/Intolerance"]' },
  { label: 'Assessment, Not Performed', insertText: '["Assessment, Not Performed"]' },
  { label: 'Assessment, Not Recommended', insertText: '["Assessment, Not Recommended"]' },
  { label: 'Device, Not Applied', insertText: '["Device, Not Applied"]' },
  { label: 'Device, Not Ordered', insertText: '["Device, Not Ordered"]' },
  { label: 'Device, Not Recommended', insertText: '["Device, Not Recommended"]' },
  { label: 'Diagnostic Study, Not Ordered', insertText: '["Diagnostic Study, Not Ordered"]' },
  { label: 'Diagnostic Study, Not Performed', insertText: '["Diagnostic Study, Not Performed"]' },
  { label: 'Diagnostic Study, Not Recommended', insertText: '["Diagnostic Study, Not Recommended"]' },
  { label: 'Encounter, Not Ordered', insertText: '["Encounter, Not Ordered"]' },
  { label: 'Encounter, Not Performed', insertText: '["Encounter, Not Performed"]' },
  { label: 'Encounter, Not Recommended', insertText: '["Encounter, Not Recommended"]' },
  { label: 'Device, Applied', insertText: '["Device, Applied"]' },
  { label: 'Immunization, Not Administered', insertText: '["Immunization, Not Administered"]' },
  { label: 'Immunization, Not Ordered', insertText: '["Immunization, Not Ordered"]' },
  { label: 'Intervention, Not Ordered', insertText: '["Intervention, Not Ordered"]' },
  { label: 'Intervention, Not Performed', insertText: '["Intervention, Not Performed"]' },
  { label: 'Intervention, Not Recommended', insertText: '["Intervention, Not Recommended"]' },
  { label: 'Laboratory Test, Not Ordered', insertText: '["Laboratory Test, Not Ordered"]' },
  { label: 'Laboratory Test, Not Performed', insertText: '["Laboratory Test, Not Performed"]' },
  { label: 'Laboratory Test, Not Recommended', insertText: '["Laboratory Test, Not Recommended"]' },
  { label: 'Medication, Not Administered', insertText: '["Medication, Not Administered"]' },
  { label: 'Medication, Not Discharged', insertText: '["Medication, Not Discharged"]' },
  { label: 'Medication, Not Dispensed', insertText: '["Medication, Not Dispensed"]' },
  { label: 'Medication, Not Ordered', insertText: '["Medication, Not Ordered"]' },
  { label: 'Physical Exam, Not Ordered', insertText: '["Physical Exam, Not Ordered"]' },
  { label: 'Physical Exam, Not Performed', insertText: '["Physical Exam, Not Performed"]' },
  { label: 'Physical Exam, Not Recommended', insertText: '["Physical Exam, Not Recommended"]' },
  { label: 'Procedure, Not Ordered', insertText: '["Procedure, Not Ordered"]' },
  { label: 'Procedure, Not Performed', insertText: '["Procedure, Not Performed"]' },
  { label: 'Procedure, Not Recommended', insertText: '["Procedure, Not Recommended"]' },
  { label: 'Substance, Not Administered', insertText: '["Substance, Not Administered"]' },
  { label: 'Substance, Not Ordered', insertText: '["Substance, Not Ordered"]' },
  { label: 'Device, Order', insertText: '["Device, Order"]' },
  { label: 'Substance, Not Recommended', insertText: '["Substance, Not Recommended"]' },
  { label: 'Participation', insertText: '["Participation"]' },
  { label: 'Assessment, Order', insertText: '["Assessment, Order"]' },
  { label: 'Assessment, Not Ordered', insertText: '["Assessment, Not Ordered"]' },
  { label: 'Communication, Performed', insertText: '["Communication, Performed"]' },
  { label: 'Communication, Not Performed', insertText: '["Communication, Not Performed"]' },
  { label: 'Diagnostic Study, Order', insertText: '["Diagnostic Study, Order"]' },
  { label: 'Diagnostic Study, Performed', insertText: '["Diagnostic Study, Performed"]' },
  { label: 'Provider Care Experience', insertText: '["Provider Care Experience"]' },
  { label: 'Encounter, Order', insertText: '["Encounter, Order"]' },
  { label: 'Encounter, Performed', insertText: '["Encounter, Performed"]' },
  { label: 'Patient Characteristic', insertText: '["Patient Characteristic"]' },
  { label: 'Provider Characteristic', insertText: '["Provider Characteristic"]' },
  { label: 'Care Goal', insertText: '["Care Goal"]' },
  { label: 'Intervention, Order', insertText: '["Intervention, Order"]' },
  { label: 'Intervention, Performed', insertText: '["Intervention, Performed"]' },
  { label: 'Laboratory Test, Order', insertText: '["Laboratory Test, Order"]' },
  { label: 'Laboratory Test, Performed', insertText: '["Laboratory Test, Performed"]' },
  { label: 'Medication, Active', insertText: '["Medication, Active"]' },
  { label: 'Medication, Administered', insertText: '["Medication, Administered"]' },
  { label: 'Medication, Dispensed', insertText: '["Medication, Dispensed"]' },
  { label: 'Medication, Order', insertText: '["Medication, Order"]' },
  { label: 'Physical Exam, Order', insertText: '["Physical Exam, Order"]' },
  { label: 'Physical Exam, Performed', insertText: '["Physical Exam, Performed"]' },
  { label: 'Procedure, Order', insertText: '["Procedure, Order"]' },
  { label: 'Procedure, Performed', insertText: '["Procedure, Performed"]' },
  { label: 'Substance, Administered', insertText: '["Substance, Administered"]' },
  { label: 'Substance, Order', insertText: '["Substance, Order"]' },
  { label: 'Device, Recommended', insertText: '["Device, Recommended"]' },
  { label: 'Encounter, Recommended', insertText: '["Encounter, Recommended"]' },
  { label: 'Intervention, Recommended', insertText: '["Intervention, Recommended"]' },
  { label: 'Laboratory Test, Recommended', insertText: '["Laboratory Test, Recommended"]' },
  { label: 'Physical Exam, Recommended', insertText: '["Physical Exam, Recommended"]' },
  { label: 'Procedure, Recommended', insertText: '["Procedure, Recommended"]' },
  { label: 'Substance, Recommended', insertText: '["Substance, Recommended"]' },
  { label: 'Diagnostic Study, Recommended', insertText: '["Diagnostic Study, Recommended"]' },
  { label: 'Patient Characteristic Birthdate', insertText: '["Patient Characteristic Birthdate"]' },
  { label: 'Patient Characteristic Expired', insertText: '["Patient Characteristic Expired"]' },
  { label: 'Patient Characteristic Clinical Trial Participant', insertText: '["Patient Characteristic Clinical Trial Participant"]' }];

export default datatypes;
