const functions = [{
  label: 'Abs()',
  insertText: 'Abs()',
}, {
  label: 'AgeInDays()',
  insertText: 'AgeInDays()',
}, {
  label: 'AgeInDaysAt()',
  insertText: 'AgeInDaysAt()',
}, {
  label: 'AgeInHours()',
  insertText: 'AgeInHours()',
}, {
  label: 'AgeInHoursAt()',
  insertText: 'AgeInHoursAt()',
}, {
  label: 'AgeInMinutes()',
  insertText: 'AgeInMinutes()',
}, {
  label: 'AgeInMinutesAt()',
  insertText: 'AgeInMinutesAt()',
}, {
  label: 'AgeInMonths()',
  insertText: 'AgeInMonths()',
}, {
  label: 'AgeInMonthsAt()',
  insertText: 'AgeInMonthsAt()',
}, {
  label: 'AgeInSeconds()',
  insertText: 'AgeInSeconds()',
}, {
  label: 'AgeInSecondsAt()',
  insertText: 'AgeInSecondsAt()',
}, {
  label: 'AgeInWeeks()',
  insertText: 'AgeInWeeks()',
}, {
  label: 'AgeInWeeksAt()',
  insertText: 'AgeInWeeksAt()',
}, {
  label: 'AgeInYears()',
  insertText: 'AgeInYears()',
}, {
  label: 'AgeInYearsAt()',
  insertText: 'AgeInYearsAt()',
}, {
  label: 'AllTrue()',
  insertText: 'AllTrue()',
}, {
  label: 'AnyTrue()',
  insertText: 'AnyTrue()',
}, {
  label: 'Avg()',
  insertText: 'Avg()',
}, {
  label: 'CalculateAgeInDays()',
  insertText: 'CalculateAgeInDays()',
}, {
  label: 'CalculateAgeInDaysAt()',
  insertText: 'CalculateAgeInDaysAt()',
}, {
  label: 'CalculateAgeInHours()',
  insertText: 'CalculateAgeInHours()',
}, {
  label: 'CalculateAgeInHoursAt()',
  insertText: 'CalculateAgeInHoursAt()',
}, {
  label: 'CalculateAgeInMinutes()',
  insertText: 'CalculateAgeInMinutes()',
}, {
  label: 'CalculateAgeInMinutesAt()',
  insertText: 'CalculateAgeInMinutesAt()',
}, {
  label: 'CalculateAgeInMonths()',
  insertText: 'CalculateAgeInMonths()',
}, {
  label: 'CalculateAgeInMonthsAt()',
  insertText: 'CalculateAgeInMonthsAt()',
}, {
  label: 'CalculateAgeInSeconds()',
  insertText: 'CalculateAgeInSecondsAt()',
}, {
  label: 'CalculateAgeInWeeks()',
  insertText: 'CalculateAgeInWeeks()',
}, {
  label: 'CalculateAgeInWeeksAt()',
  insertText: 'CalculateAgeInWeeksAt()',
}, {
  label: 'CalculateAgeInYears()',
  insertText: 'CalculateAgeInYears()',
}, {
  label: 'CalculateAgeInYearsAt()',
  insertText: 'CalculateAgeInYearsAt()',
}, {
  label: 'Ceiling()',
  insertText: 'Ceiling()',
}, {
  label: 'Coalesce()',
  insertText: 'Coalesce()',
}, {
  label: 'Count()',
  insertText: 'Count()',
}, {
  label: 'DateTime()',
  insertText: 'DateTime()',
}, {
  label: 'Exp()',
  insertText: 'Exp()',
}, {
  label: 'First()',
  insertText: 'First()',
}, {
  label: 'Floor()',
  insertText: 'Floor()',
}, {
  label: 'GeometricMean()',
  insertText: 'GeometricMean()',
}, {
  label: 'IndexOf()',
  insertText: 'IndexOf()',
}, {
  label: 'Last()',
  insertText: 'Last()',
}, {
  label: 'Length()',
  insertText: 'Length()',
}, {
  label: 'Ln()',
  insertText: 'Ln()',
}, {
  label: 'Log()',
  insertText: 'Log()',
}, {
  label: 'Max()',
  insertText: 'Max()',
}, {
  label: 'Median()',
  insertText: 'Median()',
}, {
  label: 'Min()',
  insertText: 'Min()',
}, {
  label: 'Mode()',
  insertText: 'Mode()',
}, {
  label: 'Now()',
  insertText: 'Now()',
}, {
  label: 'TesPopulationStdDevt()',
  insertText: 'PopulationStdDev()',
}, {
  label: 'PopulationVariance()',
  insertText: 'PopulationVariance()',
}, {
  label: 'Product()',
  insertText: 'Product()',
}, {
  label: 'Round()',
  insertText: 'Round()',
}, {
  label: 'StdDev()',
  insertText: 'StdDev()',
}, {
  label: 'Sum()',
  insertText: 'Sum()',
}, {
  label: 'Time()',
  insertText: 'Time()',
}, {
  label: 'TimeOfDay()',
  insertText: 'TimeOfDay()',
}, {
  label: 'Today()',
  insertText: 'Today()',
}, {
  label: 'Truncate()',
  insertText: 'Truncate()',
}, {
  label: 'Variance()',
  insertText: 'Variance()',
}];

export default functions;
