const timings = [
  { label: 'after' },
  { label: 'starts after' },
  { label: 'starts after or on' },
  { label: 'starts after or on end' },
  { label: 'starts after or on start' },
  { label: 'starts after start' },
  { label: 'starts after end' },
  { label: 'ends after' },
  { label: 'ends after start' },
  { label: 'ends after end' },
  { label: 'after start' },
  { label: 'after end' },
  { label: 'before' },
  { label: 'starts before' },
  { label: 'starts before or on' },
  { label: 'starts before or on end' },
  { label: 'starts before or on start' },
  { label: 'starts before start' },
  { label: 'starts before end' },
  { label: 'starts on or before' },
  { label: 'starts on or before end' },
  { label: 'starts on or before start' },
  { label: 'ends before' },
  { label: 'ends before start' },
  { label: 'ends before end' },
  { label: 'before start' },
  { label: 'before end' },
  { label: 'during' },
  { label: 'starts during' },
  { label: 'ends during' },
  { label: 'properly during' },
  { label: 'starts properly during' },
  { label: 'ends properly during' },
  { label: 'ends' },
  { label: 'included in' },
  { label: 'properly included in' },
  { label: 'meets' },
  { label: 'meets before' },
  { label: 'meets after' },
  { label: 'overlaps' },
  { label: 'overlaps before' },
  { label: 'overlaps after' },
  { label: 'same as' },
  { label: 'starts same as' },
  { label: 'starts same as start' },
  { label: 'starts same as end' },
  { label: 'ends same as' },
  { label: 'ends same as start' },
  { label: 'ends same as end' },
  { label: 'same as start' },
  { label: 'same as end' },
  { label: 'same or after' },
  { label: 'starts same or after' },
  { label: 'starts same or after start' },
  { label: 'starts same or after end' },
  { label: 'ends same or after' },
  { label: 'ends same or after start' },
  { label: 'ends same or after end' },
  { label: 'same or after start' },
  { label: 'same or after end' },
  { label: 'same or before' },
  { label: 'starts same or before' },
  { label: 'starts same or before start' },
  { label: 'starts same or before end' },
  { label: 'ends same or before' },
  { label: 'ends same or before start' },
  { label: 'ends same or before end' },
  { label: 'same or before start' },
  { label: 'same or before end' },
  { label: 'starts' }];

export default timings;
